import type { FromSchema, JSONSchema } from 'json-schema-to-ts'
import { SIGNAL_FAMILIES, SIGNAL_REASONS, SIGNAL_STATES } from '../types'
import { EXACT_SHA512_INTEGRITY_PATTERN, NPM_ARTIFACT_VERIFIER_SUPPORT } from './artifact-verifier'

export const APPLY_PHASE_NAMES = [
  'preflight',
  'lock',
  'manager-preflight',
  'stage',
  'precommit',
  'commit',
  'sync-lockfile',
  'install',
  'artifact-verify',
  'verify',
  'recovery',
  'inspect',
  'cleanup',
] as const

const hashSchema = { type: 'string', pattern: '^[a-f0-9]{64}$' } as const
const relativePathSchema = {
  type: 'string',
  minLength: 1,
  pattern: '^(?!/)(?![A-Za-z]:/)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*\\\\).+$',
} as const

const commonDefinitions = {
  source: {
    type: 'object',
    additionalProperties: false,
    required: ['path', 'byteHash'],
    properties: {
      path: relativePathSchema,
      byteHash: hashSchema,
    },
  },
  repository: {
    type: 'object',
    additionalProperties: false,
    required: [
      'identity',
      'fingerprint',
      'modelSchemaVersion',
      'sources',
      'boundaries',
      'sourceFiles',
      'packages',
      'catalogs',
      'runtimeDeclarations',
      'relationships',
    ],
    properties: {
      identity: { type: 'string', minLength: 1 },
      fingerprint: hashSchema,
      modelSchemaVersion: { const: 1 },
      sources: { type: 'array', items: { $ref: '#/definitions/source' } },
      root: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'path', 'discoveryMode', 'evidenceId'],
        properties: {
          id: { type: 'string', minLength: 1 },
          path: { const: '.' },
          discoveryMode: { enum: ['direct-root', 'inside-project', 'parent-folder'] },
          evidenceId: { type: 'string', minLength: 1 },
        },
      },
      boundaries: { type: 'array', items: { $ref: '#/definitions/boundary' } },
      sourceFiles: { type: 'array', items: { $ref: '#/definitions/sourceFile' } },
      packages: { type: 'array', items: { $ref: '#/definitions/package' } },
      catalogs: { type: 'array', items: { $ref: '#/definitions/catalog' } },
      runtimeDeclarations: {
        type: 'array',
        items: { $ref: '#/definitions/runtimeDeclaration' },
      },
      relationships: { $ref: '#/definitions/relationships' },
    },
  },
  boundary: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'path', 'classification', 'markers'],
    properties: {
      id: { type: 'string', minLength: 1 },
      path: relativePathSchema,
      classification: { enum: ['effective-root', 'nested-workspace', 'nested-git'] },
      markers: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['id', 'kind', 'path'],
          properties: {
            id: { type: 'string', minLength: 1 },
            kind: {
              enum: ['pnpm-workspace', 'yarn-workspace', 'manifest-workspaces', 'git-repo'],
            },
            path: relativePathSchema,
          },
        },
      },
    },
  },
  sourceFile: {
    type: 'object',
    additionalProperties: false,
    required: [
      'id',
      'path',
      'format',
      'byteHash',
      'parseState',
      'indent',
      'newline',
      'trailingNewline',
    ],
    properties: {
      id: { type: 'string', minLength: 1 },
      path: relativePathSchema,
      format: { enum: ['json', 'yaml'] },
      byteHash: hashSchema,
      parseState: { enum: ['parsed', 'error'] },
      indent: { type: 'string' },
      newline: { enum: ['lf', 'crlf', 'mixed', 'none'] },
      trailingNewline: { type: 'boolean' },
    },
  },
  package: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'sourceFileId', 'path', 'workspacePath', 'name', 'private'],
    properties: {
      id: { type: 'string', minLength: 1 },
      sourceFileId: { type: 'string', minLength: 1 },
      path: relativePathSchema,
      workspacePath: relativePathSchema,
      name: { type: 'string' },
      private: { type: 'boolean' },
    },
  },
  catalog: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'sourceFileId', 'manager', 'format', 'name', 'entries'],
    properties: {
      id: { type: 'string', minLength: 1 },
      sourceFileId: { type: 'string', minLength: 1 },
      manager: { enum: ['pnpm', 'bun', 'yarn'] },
      format: { enum: ['json', 'yaml'] },
      name: { type: 'string' },
      entries: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['name', 'occurrenceId'],
          properties: {
            name: { type: 'string', minLength: 1 },
            occurrenceId: { type: 'string', minLength: 1 },
          },
        },
      },
    },
  },
  runtimeDeclaration: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'boundaryId', 'kind', 'path', 'declaredText'],
    properties: {
      id: { type: 'string', minLength: 1 },
      boundaryId: { type: 'string', minLength: 1 },
      kind: { enum: ['engines-node', 'nvmrc', 'node-version', 'tool-versions-nodejs'] },
      path: relativePathSchema,
      field: { type: 'string' },
      declaredText: { type: 'string' },
      byteHash: hashSchema,
    },
  },
  relationships: {
    type: 'object',
    additionalProperties: false,
    required: ['workspaceMembers', 'catalogConsumers', 'boundaryPackages', 'lockfileBoundaries'],
    properties: {
      workspaceMembers: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['workspaceId', 'packageId'],
          properties: {
            workspaceId: { type: 'string', minLength: 1 },
            packageId: { type: 'string', minLength: 1 },
          },
        },
      },
      catalogConsumers: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['catalogId', 'occurrenceId'],
          properties: {
            catalogId: { type: 'string', minLength: 1 },
            occurrenceId: { type: 'string', minLength: 1 },
          },
        },
      },
      boundaryPackages: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['boundaryId', 'packageId'],
          properties: {
            boundaryId: { type: 'string', minLength: 1 },
            packageId: { type: 'string', minLength: 1 },
          },
        },
      },
      lockfileBoundaries: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['lockfileId', 'boundaryId'],
          properties: {
            lockfileId: { type: 'string', minLength: 1 },
            boundaryId: { type: 'string', minLength: 1 },
          },
        },
      },
    },
  },
  diagnostic: {
    type: 'object',
    additionalProperties: false,
    required: ['code', 'path'],
    properties: {
      code: { type: 'string', minLength: 1 },
      path: relativePathSchema,
      detail: { type: 'string' },
    },
  },
  occurrence: {
    type: 'object',
    additionalProperties: false,
    required: [
      'id',
      'ownerId',
      'sourceFileId',
      'file',
      'name',
      'path',
      'field',
      'role',
      'protocol',
      'declaredValue',
      'writeable',
    ],
    properties: {
      id: { type: 'string', minLength: 1 },
      ownerId: { type: 'string', minLength: 1 },
      sourceFileId: { type: 'string', minLength: 1 },
      file: relativePathSchema,
      name: { type: 'string', minLength: 1 },
      path: { type: 'array', minItems: 1, items: { type: 'string' } },
      field: { type: 'string', minLength: 1 },
      role: {
        enum: [
          'dependency',
          'override',
          'package-manager',
          'catalog-owner',
          'catalog-consumer',
          'global',
        ],
      },
      protocol: {
        enum: [
          'semver',
          'npm',
          'jsr',
          'github',
          'workspace',
          'catalog',
          'file',
          'link',
          'git',
          'http',
          'unknown',
        ],
      },
      declaredValue: { type: 'string' },
      writeable: { type: 'boolean' },
      catalogId: { type: 'string', minLength: 1 },
    },
  },
  evidence: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'kind', 'status', 'values', 'sources', 'diagnostics'],
    properties: {
      id: { type: 'string', minLength: 1 },
      kind: {
        enum: ['root', 'workspace', 'package-manager', 'lockfile-selection', 'runtime', 'vcs'],
      },
      boundaryId: { type: 'string', minLength: 1 },
      status: { enum: ['confirmed', 'ambiguous', 'missing', 'unsupported', 'unavailable'] },
      values: { type: 'array', items: { $ref: '#/definitions/jsonValue' } },
      sources: { type: 'array', items: { $ref: '#/definitions/evidenceSource' } },
      diagnostics: { type: 'array', items: { $ref: '#/definitions/diagnostic' } },
    },
  },
  evidenceSource: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'kind', 'path'],
    properties: {
      id: { type: 'string', minLength: 1 },
      kind: { enum: ['file', 'field', 'probe'] },
      path: relativePathSchema,
      field: { type: 'array', items: { type: 'string' } },
      probe: { enum: ['discovery', 'git'] },
      byteHash: hashSchema,
    },
  },
  jsonValue: {
    anyOf: [
      { type: 'null' },
      { type: 'boolean' },
      { type: 'number' },
      { type: 'string' },
      { type: 'array' },
      { type: 'object' },
    ],
  },
  lockfile: {
    type: 'object',
    additionalProperties: false,
    required: ['id', 'boundaryId', 'manager', 'path', 'parseState'],
    properties: {
      id: { type: 'string', minLength: 1 },
      boundaryId: { type: 'string', minLength: 1 },
      manager: { enum: ['npm', 'pnpm', 'yarn', 'bun'] },
      path: relativePathSchema,
      byteHash: hashSchema,
      parseState: { enum: ['parsed', 'error', 'unsupported', 'unavailable'] },
      formatVersion: { type: 'string' },
    },
  },
  vcs: {
    type: 'object',
    additionalProperties: false,
    required: ['status', 'targetFiles', 'unrelatedDirtyPaths', 'diagnostics'],
    properties: {
      status: { enum: ['confirmed', 'unavailable'] },
      shallow: { type: 'boolean' },
      targetFiles: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['path', 'state'],
          properties: {
            path: relativePathSchema,
            state: {
              enum: [
                'clean',
                'staged',
                'unstaged',
                'staged-plus-unstaged',
                'added',
                'deleted',
                'renamed',
                'conflicted',
                'untracked',
                'ignored',
              ],
            },
            originalPath: relativePathSchema,
          },
        },
      },
      unrelatedDirtyPaths: { type: 'array', items: relativePathSchema },
      diagnostics: { type: 'array', items: { $ref: '#/definitions/diagnostic' } },
    },
  },
  error: {
    type: 'object',
    additionalProperties: false,
    required: ['code', 'reason', 'message', 'retryable', 'fatal'],
    properties: {
      code: { type: 'string', minLength: 1 },
      reason: { type: 'string', minLength: 1 },
      message: { type: 'string' },
      retryable: { type: 'boolean' },
      fatal: { type: 'boolean' },
      occurrenceId: { type: 'string', minLength: 1 },
    },
  },
  risk: {
    type: 'object',
    additionalProperties: false,
    required: ['code', 'severity', 'message', 'evidenceRefs'],
    properties: {
      code: { type: 'string', minLength: 1 },
      severity: { enum: ['info', 'warning', 'blocking'] },
      message: { type: 'string' },
      occurrenceId: { type: 'string', minLength: 1 },
      evidenceRefs: { type: 'array', items: { type: 'string', minLength: 1 } },
    },
  },
} as const

export const INSPECT_SCHEMA_ID = 'https://depfresh.dev/schemas/inspect-v1.schema.json'
export const PLAN_SCHEMA_ID = 'https://depfresh.dev/schemas/plan-v1.schema.json'
export const APPLY_SCHEMA_ID = 'https://depfresh.dev/schemas/apply-v1.schema.json'
export const COMMAND_ERROR_SCHEMA_ID = 'https://depfresh.dev/schemas/error-v1.schema.json'

export const inspectResultSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: INSPECT_SCHEMA_ID,
  title: 'depfresh inspect contract v1',
  type: 'object',
  additionalProperties: false,
  required: [
    'contract',
    'schemaVersion',
    'toolVersion',
    'repository',
    'occurrences',
    'evidence',
    'lockfiles',
    'vcs',
    'diagnostics',
    'risks',
    'errors',
    'requiredCapabilities',
  ],
  properties: {
    contract: { const: 'depfresh.inspect' },
    schemaVersion: { const: 1 },
    toolVersion: { type: 'string', minLength: 1 },
    repository: { $ref: '#/definitions/repository' },
    occurrences: { type: 'array', items: { $ref: '#/definitions/occurrence' } },
    evidence: { type: 'array', items: { $ref: '#/definitions/evidence' } },
    lockfiles: { type: 'array', items: { $ref: '#/definitions/lockfile' } },
    vcs: { $ref: '#/definitions/vcs' },
    diagnostics: { type: 'array', items: { $ref: '#/definitions/diagnostic' } },
    risks: { type: 'array', items: { $ref: '#/definitions/risk' } },
    errors: { type: 'array', items: { $ref: '#/definitions/error' } },
    requiredCapabilities: {
      type: 'array',
      items: { enum: ['filesystem-read'] },
    },
  },
  definitions: commonDefinitions,
} as const satisfies JSONSchema

const policyDecisionSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['status', 'reason', 'action', 'mode', 'matchedRuleIds', 'indeterminateRuleIds'],
  properties: {
    status: { enum: ['selected', 'skipped', 'blocked', 'unchanged'] },
    reason: {
      enum: [
        'POLICY_DEFAULT_INCLUDED',
        'POLICY_RULE_INCLUDED',
        'POLICY_RULE_EXCLUDED',
        'POLICY_MANAGER_UNKNOWN',
        'POLICY_CANDIDATE_UNCHANGED',
      ],
    },
    action: { enum: ['include', 'exclude'] },
    mode: { enum: ['default', 'major', 'minor', 'patch', 'latest', 'newest', 'next'] },
    matchedRuleIds: { type: 'array', items: { type: 'string' } },
    indeterminateRuleIds: { type: 'array', items: { type: 'string' } },
    winningActionRuleId: { type: 'string' },
    winningModeRuleId: { type: 'string' },
    candidateReason: { type: 'string' },
  },
} as const

const signalRuleInputSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'selectors', 'effect'],
  properties: {
    id: { type: 'string', minLength: 1 },
    selectors: {
      type: 'object',
      additionalProperties: false,
      minProperties: 1,
      properties: {
        family: { enum: SIGNAL_FAMILIES },
        state: { enum: SIGNAL_STATES },
        reason: { enum: SIGNAL_REASONS },
        dependencyName: { type: 'string', minLength: 1 },
        workspacePath: relativePathSchema,
        cohortId: { type: 'string', minLength: 1 },
      },
    },
    effect: { enum: ['warn', 'block'] },
  },
} as const

const planExecutionSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['mode', 'status', 'timeoutMs', 'targets'],
  properties: {
    mode: { enum: ['file-only', 'sync-lockfile', 'install'] },
    status: { enum: ['ready', 'blocked', 'not-needed'] },
    timeoutMs: { type: 'integer', minimum: 1, maximum: 600000 },
    reason: { type: 'string', minLength: 1 },
    targets: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['boundaryId', 'boundaryPath', 'manager', 'lockfile', 'adapter'],
        properties: {
          boundaryId: { type: 'string', minLength: 1 },
          boundaryPath: relativePathSchema,
          manager: {
            type: 'object',
            additionalProperties: false,
            required: ['name', 'version'],
            properties: {
              name: { enum: ['npm', 'pnpm', 'bun'] },
              version: { type: 'string', minLength: 1 },
            },
          },
          lockfile: {
            type: 'object',
            additionalProperties: false,
            required: ['id', 'path', 'byteHash'],
            properties: {
              id: { type: 'string', minLength: 1 },
              path: relativePathSchema,
              byteHash: hashSchema,
            },
          },
          adapter: {
            type: 'object',
            additionalProperties: false,
            required: ['executable', 'args', 'lifecycle', 'permittedPaths', 'externalEffects'],
            properties: {
              executable: { enum: ['npm', 'pnpm', 'bun'] },
              args: { type: 'array', minItems: 1, items: { type: 'string' } },
              lifecycle: {
                enum: ['disabled-by-flag', 'disabled-by-flag-and-pnpmfile-bypass'],
              },
              permittedPaths: { type: 'array', minItems: 1, items: relativePathSchema },
              externalEffects: {
                type: 'array',
                items: { enum: ['package-manager-cache', 'dependency-install-state'] },
              },
            },
          },
        },
      },
    },
    verification: {
      type: 'object',
      additionalProperties: false,
      required: ['executable', 'args', 'cwd', 'timeoutMs', 'permittedPaths'],
      properties: {
        executable: { type: 'string', minLength: 1 },
        args: { type: 'array', items: { type: 'string' } },
        cwd: relativePathSchema,
        timeoutMs: { type: 'integer', minimum: 1, maximum: 600000 },
        permittedPaths: { type: 'array', maxItems: 0, items: relativePathSchema },
      },
    },
    artifactVerification: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'timeoutMs', 'isolatedHome', 'policySource', 'rules', 'targets'],
      properties: {
        kind: { const: 'npm-audit-signatures-v1' },
        timeoutMs: { type: 'integer', minimum: 1, maximum: 600000 },
        isolatedHome: { const: true },
        policySource: { enum: ['config', 'library', 'cli'] },
        rules: { type: 'array', items: signalRuleInputSchema },
        targets: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            additionalProperties: false,
            required: ['boundaryId', 'cwd', 'verifier', 'executable', 'args', 'artifacts'],
            properties: {
              boundaryId: { type: 'string', minLength: 1 },
              cwd: relativePathSchema,
              verifier: {
                type: 'object',
                additionalProperties: false,
                required: ['name', 'version'],
                properties: {
                  name: { const: 'npm' },
                  version: { type: 'string', minLength: 1 },
                },
              },
              executable: { const: 'npm' },
              args: {
                const: [
                  'audit',
                  'signatures',
                  '--json',
                  '--include-attestations',
                  '--ignore-scripts',
                ],
              },
              artifacts: {
                type: 'array',
                minItems: 1,
                items: {
                  type: 'object',
                  additionalProperties: false,
                  required: [
                    'id',
                    'occurrenceIds',
                    'packageName',
                    'version',
                    'registry',
                    'integrity',
                    'signaturePresence',
                    'provenancePresence',
                    'evidenceRef',
                  ],
                  properties: {
                    id: { type: 'string', pattern: '^artifact-[a-f0-9]{24}$' },
                    occurrenceIds: {
                      type: 'array',
                      minItems: 1,
                      uniqueItems: true,
                      items: { type: 'string', minLength: 1 },
                    },
                    packageName: { type: 'string', minLength: 1 },
                    version: { type: 'string', minLength: 1 },
                    registry: { const: NPM_ARTIFACT_VERIFIER_SUPPORT.registry },
                    integrity: { type: 'string', pattern: EXACT_SHA512_INTEGRITY_PATTERN },
                    signaturePresence: { enum: ['present', 'absent', 'unknown'] },
                    provenancePresence: { enum: ['present', 'absent', 'unknown'] },
                    evidenceRef: {
                      type: 'string',
                      pattern: '^signal-evidence-[a-f0-9]{24}$',
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
} as const

const signalEvidenceSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'kind', 'status', 'subject', 'sourceRefs', 'facts'],
  properties: {
    id: { type: 'string', pattern: '^signal-evidence-[a-f0-9]{24}$' },
    kind: {
      enum: [
        'repository-runtime',
        'registry-version',
        'planned-graph',
        'explicit-cohort',
        'inferred-cohort',
        'clock',
        'registry-artifact',
      ],
    },
    status: { enum: ['observed', 'absent', 'unknown', 'conflicting'] },
    subject: { type: 'string', minLength: 1 },
    sourceRefs: { type: 'array', items: { type: 'string', minLength: 1 } },
    facts: {
      type: 'object',
      propertyNames: { type: 'string', minLength: 1 },
      additionalProperties: { type: 'string' },
    },
  },
} as const

const planSignalSchema = {
  type: 'object',
  additionalProperties: false,
  required: [
    'id',
    'family',
    'state',
    'reason',
    'subject',
    'evidenceRefs',
    'effect',
    'matchedRuleIds',
  ],
  properties: {
    id: { type: 'string', pattern: '^signal-[a-f0-9]{24}$' },
    family: { enum: SIGNAL_FAMILIES },
    state: { enum: SIGNAL_STATES },
    reason: { enum: SIGNAL_REASONS },
    subject: {
      type: 'object',
      additionalProperties: false,
      required: ['occurrenceIds'],
      properties: {
        occurrenceIds: { type: 'array', items: { type: 'string', minLength: 1 } },
        dependencyName: { type: 'string', minLength: 1 },
        workspacePath: relativePathSchema,
        cohortId: { type: 'string', minLength: 1 },
      },
    },
    evidenceRefs: { type: 'array', minItems: 1, items: { type: 'string', minLength: 1 } },
    effect: { enum: ['none', 'warn', 'block'] },
    matchedRuleIds: { type: 'array', items: { type: 'string', minLength: 1 } },
    winningRuleId: { type: 'string', minLength: 1 },
    override: {
      type: 'object',
      additionalProperties: false,
      required: ['ruleId', 'source', 'from', 'to'],
      properties: {
        ruleId: { type: 'string', minLength: 1 },
        source: { enum: ['config', 'library', 'cli'] },
        from: { enum: ['none', 'warn', 'block'] },
        to: { enum: ['warn', 'block'] },
      },
    },
  },
} as const

const signalSummarySchema = {
  type: 'object',
  additionalProperties: false,
  required: ['total', 'pass', 'warn', 'fail', 'unknown', 'notApplicable', 'blocking'],
  properties: {
    total: { type: 'integer', minimum: 0 },
    pass: { type: 'integer', minimum: 0 },
    warn: { type: 'integer', minimum: 0 },
    fail: { type: 'integer', minimum: 0 },
    unknown: { type: 'integer', minimum: 0 },
    notApplicable: { type: 'integer', minimum: 0 },
    blocking: { type: 'integer', minimum: 0 },
  },
} as const

export const planResultSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: PLAN_SCHEMA_ID,
  title: 'depfresh plan contract v1',
  type: 'object',
  additionalProperties: false,
  required: [
    'contract',
    'schemaVersion',
    'toolVersion',
    'repository',
    'asOf',
    'occurrences',
    'decisions',
    'operations',
    'execution',
    'evidence',
    'lockfiles',
    'vcs',
    'diagnostics',
    'risks',
    'errors',
    'requiredCapabilities',
    'summary',
    'planFingerprint',
  ],
  properties: {
    contract: { const: 'depfresh.plan' },
    schemaVersion: { const: 1 },
    toolVersion: { type: 'string', minLength: 1 },
    repository: { $ref: '#/definitions/repository' },
    asOf: {
      type: 'string',
      pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$',
    },
    occurrences: { type: 'array', items: { $ref: '#/definitions/occurrence' } },
    decisions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['occurrenceId', 'status', 'reason', 'policy'],
        properties: {
          occurrenceId: { type: 'string', minLength: 1 },
          status: { enum: ['operation', 'unchanged', 'skipped', 'blocked', 'unknown', 'error'] },
          reason: { type: 'string', minLength: 1 },
          operationId: { type: 'string', minLength: 1 },
          candidate: {
            type: 'object',
            additionalProperties: false,
            required: ['reason', 'eligibleVersions'],
            properties: {
              reason: { type: 'string', minLength: 1 },
              eligibleVersions: { type: 'array', items: { type: 'string' } },
              targetVersion: { type: 'string' },
            },
          },
          policy: policyDecisionSchema,
        },
      },
    },
    operations: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'id',
          'occurrenceId',
          'sourceFileId',
          'file',
          'path',
          'name',
          'sourceByteHash',
          'expectedValue',
          'requestedValue',
        ],
        properties: {
          id: { type: 'string', minLength: 1 },
          occurrenceId: { type: 'string', minLength: 1 },
          sourceFileId: { type: 'string', minLength: 1 },
          file: relativePathSchema,
          path: { type: 'array', minItems: 1, items: { type: 'string' } },
          name: { type: 'string', minLength: 1 },
          sourceByteHash: hashSchema,
          expectedValue: { type: 'string' },
          requestedValue: { type: 'string' },
        },
      },
    },
    signals: { type: 'array', items: planSignalSchema },
    signalEvidence: { type: 'array', items: signalEvidenceSchema },
    execution: planExecutionSchema,
    evidence: { type: 'array', items: { $ref: '#/definitions/evidence' } },
    lockfiles: { type: 'array', items: { $ref: '#/definitions/lockfile' } },
    vcs: { $ref: '#/definitions/vcs' },
    diagnostics: { type: 'array', items: { $ref: '#/definitions/diagnostic' } },
    risks: { type: 'array', items: { $ref: '#/definitions/risk' } },
    errors: { type: 'array', items: { $ref: '#/definitions/error' } },
    requiredCapabilities: {
      type: 'array',
      items: {
        enum: [
          'filesystem-read',
          'registry-read',
          'file-write',
          'process-execute',
          'lockfile-write',
          'install',
          'verify-command',
          'artifact-verify',
          'network-access',
        ],
      },
    },
    summary: {
      type: 'object',
      additionalProperties: false,
      required: ['total', 'operations', 'unchanged', 'skipped', 'blocked', 'unknown', 'errors'],
      properties: {
        total: { type: 'integer', minimum: 0 },
        operations: { type: 'integer', minimum: 0 },
        unchanged: { type: 'integer', minimum: 0 },
        skipped: { type: 'integer', minimum: 0 },
        blocked: { type: 'integer', minimum: 0 },
        unknown: { type: 'integer', minimum: 0 },
        errors: { type: 'integer', minimum: 0 },
        signals: signalSummarySchema,
      },
    },
    planFingerprint: hashSchema,
  },
  definitions: commonDefinitions,
} as const satisfies JSONSchema

const writeOutcomeSummarySchema = {
  type: 'object',
  additionalProperties: false,
  required: ['planned', 'applied', 'skipped', 'conflicted', 'reverted', 'failed', 'unknown'],
  properties: {
    planned: { type: 'integer', minimum: 0 },
    applied: { type: 'integer', minimum: 0 },
    skipped: { type: 'integer', minimum: 0 },
    conflicted: { type: 'integer', minimum: 0 },
    reverted: { type: 'integer', minimum: 0 },
    failed: { type: 'integer', minimum: 0 },
    unknown: { type: 'integer', minimum: 0 },
  },
} as const

export const applyResultSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: APPLY_SCHEMA_ID,
  title: 'depfresh apply contract v1',
  type: 'object',
  additionalProperties: false,
  required: [
    'contract',
    'schemaVersion',
    'toolVersion',
    'planFingerprint',
    'repositoryIdentity',
    'status',
    'operations',
    'phases',
    'summary',
    'recovery',
    'requiredCapabilities',
  ],
  properties: {
    contract: { const: 'depfresh.apply' },
    schemaVersion: { const: 1 },
    toolVersion: { type: 'string', minLength: 1 },
    planFingerprint: hashSchema,
    repositoryIdentity: { type: 'string', minLength: 1 },
    status: { enum: ['applied', 'noop', 'conflicted', 'reverted', 'failed', 'unknown'] },
    operations: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'operationId',
          'occurrenceId',
          'sourceFileId',
          'file',
          'path',
          'name',
          'expectedValue',
          'requestedValue',
          'status',
          'reason',
        ],
        properties: {
          operationId: { type: 'string', minLength: 1 },
          occurrenceId: { type: 'string', minLength: 1 },
          sourceFileId: { type: 'string', minLength: 1 },
          file: relativePathSchema,
          path: { type: 'array', minItems: 1, items: { type: 'string' } },
          name: { type: 'string', minLength: 1 },
          expectedValue: { type: 'string' },
          requestedValue: { type: 'string' },
          observedValue: { type: 'string' },
          observedByteHash: hashSchema,
          status: {
            enum: ['applied', 'skipped', 'conflicted', 'reverted', 'failed', 'unknown'],
          },
          reason: { type: 'string', minLength: 1 },
        },
      },
    },
    phases: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'status', 'reason'],
        properties: {
          name: { enum: APPLY_PHASE_NAMES },
          status: { enum: ['passed', 'skipped', 'failed', 'unknown'] },
          reason: { type: 'string', minLength: 1 },
          commands: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: [
                'cwd',
                'executable',
                'args',
                'termination',
                'terminationConfirmed',
                'changedPaths',
                'unexpectedPaths',
                'externalEffects',
              ],
              properties: {
                boundaryId: { type: 'string', minLength: 1 },
                manager: { enum: ['npm', 'pnpm', 'bun'] },
                managerVersion: { type: 'string', minLength: 1 },
                lifecycle: {
                  enum: ['disabled-by-flag', 'disabled-by-flag-and-pnpmfile-bypass'],
                },
                cwd: relativePathSchema,
                executable: { type: 'string', minLength: 1 },
                args: { type: 'array', items: { type: 'string' } },
                termination: {
                  enum: ['exit', 'signal', 'timeout', 'unavailable', 'unknown'],
                },
                terminationConfirmed: { type: 'boolean' },
                exitCode: { type: 'integer' },
                signal: { type: 'string', minLength: 1 },
                changedPaths: { type: 'array', items: relativePathSchema },
                unexpectedPaths: { type: 'array', items: relativePathSchema },
                lockfile: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['path', 'parseState', 'occurrences'],
                  properties: {
                    path: relativePathSchema,
                    byteHash: hashSchema,
                    parseState: { enum: ['parsed', 'error', 'unsupported', 'unavailable'] },
                    occurrences: { enum: ['matched', 'mismatched', 'not-checked'] },
                  },
                },
                externalEffects: {
                  type: 'array',
                  items: { enum: ['package-manager-cache', 'dependency-install-state'] },
                },
              },
            },
          },
          artifactResults: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              additionalProperties: false,
              required: [
                'artifactId',
                'boundaryId',
                'location',
                'packageName',
                'version',
                'registry',
                'integrity',
                'lockfile',
                'verifier',
                'observedAt',
                'signature',
                'provenance',
              ],
              properties: {
                artifactId: { type: 'string', pattern: '^artifact-[a-f0-9]{24}$' },
                boundaryId: { type: 'string', minLength: 1 },
                location: relativePathSchema,
                packageName: { type: 'string', minLength: 1 },
                version: { type: 'string', minLength: 1 },
                registry: { const: NPM_ARTIFACT_VERIFIER_SUPPORT.registry },
                integrity: { type: 'string', pattern: EXACT_SHA512_INTEGRITY_PATTERN },
                lockfile: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['path', 'byteHash'],
                  properties: { path: relativePathSchema, byteHash: hashSchema },
                },
                verifier: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['name', 'version'],
                  properties: { name: { const: 'npm' }, version: { type: 'string' } },
                },
                observedAt: {
                  type: 'string',
                  pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$',
                },
                signature: { $ref: '#/definitions/artifactTrustDimension' },
                provenance: { $ref: '#/definitions/artifactTrustDimension' },
              },
            },
          },
        },
      },
    },
    summary: writeOutcomeSummarySchema,
    recovery: {
      type: 'object',
      additionalProperties: false,
      required: ['status'],
      properties: {
        status: { enum: ['not-needed', 'completed', 'partial', 'unknown'] },
        journalId: { type: 'string', minLength: 1 },
        restoredPaths: { type: 'array', items: relativePathSchema },
        unrecoveredPaths: { type: 'array', items: relativePathSchema },
        externalEffects: {
          type: 'array',
          items: { enum: ['package-manager-cache', 'dependency-install-state'] },
        },
      },
    },
    requiredCapabilities: {
      type: 'array',
      items: {
        enum: [
          'filesystem-read',
          'file-write',
          'process-execute',
          'lockfile-write',
          'install',
          'verify-command',
          'artifact-verify',
          'network-access',
        ],
      },
    },
  },
  definitions: {
    ...commonDefinitions,
    artifactTrustDimension: {
      type: 'object',
      additionalProperties: false,
      required: ['state', 'reason', 'effect', 'matchedRuleIds'],
      properties: {
        state: { enum: SIGNAL_STATES },
        reason: { enum: SIGNAL_REASONS },
        effect: { enum: ['none', 'warn', 'block'] },
        matchedRuleIds: { type: 'array', items: { type: 'string', minLength: 1 } },
        winningRuleId: { type: 'string', minLength: 1 },
      },
    },
  },
} as const satisfies JSONSchema

export const commandErrorSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: COMMAND_ERROR_SCHEMA_ID,
  title: 'depfresh machine command error v1',
  type: 'object',
  additionalProperties: false,
  required: ['contract', 'schemaVersion', 'toolVersion', 'command', 'errors'],
  properties: {
    contract: { const: 'depfresh.error' },
    schemaVersion: { const: 1 },
    toolVersion: { type: 'string', minLength: 1 },
    command: { enum: ['inspect', 'plan', 'apply'] },
    errors: { type: 'array', minItems: 1, items: { $ref: '#/definitions/error' } },
  },
  definitions: commonDefinitions,
} as const satisfies JSONSchema

export type InspectResult = FromSchema<typeof inspectResultSchema>
export type PlanResult = FromSchema<typeof planResultSchema>
export type ApplyResult = FromSchema<typeof applyResultSchema>
export type MachineCommandError = FromSchema<typeof commandErrorSchema>
